version: '3'

services:

  backend:
    build:
      context: .
    env_file:
      - .env
    command: ["gunicorn", "blog_backend.wsgi", "--bind", "0.0.0.0:8000"]
    ports:
      - "0.0.0.0:8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    volumes:
      - build_folder:/frontend/build

  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:8080"
    volumes:
      - ./webserver/:/etc/nginx/conf.d/:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  build_folder: {}